classicmodels_modeling:
  target: source  
  outputs:
    source:
      type: postgres
      threads: 1
      host: de-c4w4lab1-rds.cxymcq60kv31.us-east-1.rds.amazonaws.com
      port: 5432
      dbname: postgres
      schema: classicmodels
      user: postgresuser
      password: adminpwrd